# Generated by Django 5.0 on 2023-12-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0003_alter_contact_eml_alter_contact_fn_alter_contact_ln_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(blank=True, max_length=255, null=True)),
                ('ln', models.CharField(max_length=255)),
                ('eml', models.EmailField(max_length=254)),
                ('adr', models.CharField(max_length=255)),
                ('cont', models.CharField(max_length=255)),
                ('post', models.IntegerField()),
                ('pho', models.CharField(max_length=20)),
                ('sub', models.CharField(max_length=255)),
                ('coupon', models.IntegerField(default=0)),
            ],
        ),
    ]
