# Generated by Django 5.0 on 2023-12-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0004_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sub',
        ),
    ]
