# Generated by Django 5.0 on 2023-12-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0005_remove_client_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pas',
            field=models.CharField(default='', max_length=255),
        ),
    ]
