# Generated by Django 5.0 on 2023-12-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0006_client_pas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adr',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='cont',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='eml',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='ln',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='pho',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='post',
            field=models.IntegerField(default=0),
        ),
    ]
