# Generated by Django 5.0 on 2023-12-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0007_alter_client_adr_alter_client_cont_alter_client_eml_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adr',
            field=models.CharField(blank=True, default='_derb friha', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cont',
            field=models.CharField(blank=True, default='_egypt', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='coupon',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='eml',
            field=models.EmailField(blank=True, default='_o@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='fn',
            field=models.CharField(blank=True, default='_oussama', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='ln',
            field=models.CharField(blank=True, default='_naya', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pas',
            field=models.CharField(blank=True, default='_5555', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='pho',
            field=models.CharField(blank=True, default='_0777', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='post',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
