# Generated by Django 5.0 on 2023-12-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0008_alter_client_adr_alter_client_cont_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='coupon',
            new_name='percentage_remis',
        ),
        migrations.AddField(
            model_name='client',
            name='code_remis',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
