# Generated by Django 5.0 on 2023-12-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0009_rename_coupon_client_percentage_remis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ln', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('eml', models.EmailField(blank=True, default='_o@gmail.com', max_length=254, null=True)),
                ('produit_name', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
