# Generated by Django 5.0 on 2023-12-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0010_command'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='fn',
            new_name='fnn',
        ),
    ]
