# Generated by Django 5.0 on 2023-12-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0011_rename_fn_command_fnn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='fnn',
            new_name='fn',
        ),
    ]
