# Generated by Django 5.0 on 2023-12-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0012_rename_fnn_command_fn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Command',
            new_name='Commande',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='produit_name',
            new_name='p_name',
        ),
    ]
