# Generated by Django 5.0 on 2023-12-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0013_rename_command_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='p_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
