# Generated by Django 5.0 on 2023-12-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_test_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantite',
            field=models.IntegerField(default=0, max_length=1000),
        ),
    ]
