# Generated by Django 5.0 on 2023-12-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
