# Generated by Django 5.0 on 2023-12-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='new',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
    ]
